import time


def FirstPythonLesson():
    print(
        "Python is one of the most versatile programming languages to date. It has complex applications, but is simple to learn.")
    time.sleep(2)
    Reply = input("shall we get started? Yes or No? Type your answer: ")
    replies = ['Yes', 'yes']
    if Reply in replies:
        print("Okay! Let's do this")
        time.sleep(2)
        print("Now you are going to build your first Python application")
        time.sleep(4)
        print("This application will use the 'print' function, which allows text to be printed.")
        print("'print' must be accompanied by parenthesis '()' like this 'print()'")
        time.sleep(3)
        def question1():
            answer = input("type it out:")
            if answer == 'print()':
                print("Output: print()")
                print("correct!")
                time.sleep(2)
            else:
                print("Lets try that again!")
                time.sleep(1)
                question1()
        question1()
        print("Now, we will expand upon this knowledge to create your first application: a Python script that prints out text by command, which is exactly the reason why you are able to read")
        time.sleep(5)
        print("THIS!")
        time.sleep(4)
        print("Well, we just learned what the 'print()' function is, but how do we tell it to produce an output?")
        time.sleep(2)
        print("Aha!")
        time.sleep(2)
        print("We must put text in between the parenthesis for it to be executed, just like this:")
        time.sleep(1.5)
        print('print("Hello World")')
        def question2():
            answer = input("Let's try it:")
            if answer == 'print("Hello World")':
                print("Output: Hello World")
                time.sleep(1.5)
                print('correct!')
                time.sleep(3)
            else:
                print("That's not quite it. Try again!")
                print("Did you forget your quotation marks perhaps?")
                time.sleep(1)
                question2()
        question2()
        print("While we used double quotation marks on our function like this:")
        time.sleep(2)
        print('("Hello World")')
        time.sleep(2)
        print("It's still totally okay to address your function using single quotation marks:")
        time.sleep(2)
        print("('hello world')")
        time.sleep(2)
        print("UNLESS... there's an apostrophe in your argument. We wouldn't want the program to get 'confused' by interpreting the apostrophe in the word as the end of the argument:")
        time.sleep(3)
        print("Wrong = 'There's the car!'")
        time.sleep(2.5)
        print("Anyhow, this is it!")
        time.sleep(3)
        print("Congratulations on completing your first tutorial in Python!")
        time.sleep(4)
        print("You learned what a function is and how the 'print' function can produce an output")
        time.sleep(1.5)
        print("And as a result, you made your first application! Bravo!")
        time.sleep(1)
        print("To celebrate, I think it's time to cue the victory music...")
        time.sleep(1.5)
        print("In 3...")
        time.sleep(1)
        print("2...")
        time.sleep(1)
        print("1...")
        time.sleep(1)
        print("Volume Up!")
        time.sleep(.75)
        from playsound import playsound
        playsound('Victory.mp3')
        time.sleep(1)
        print("Song Credits: https://www.youtube.com/watch?v=k9iYm9PEAHg")
        time.sleep(1.5)
        print("Thank you all very much, I hope you enjoy my Capstone Project!")
        time.sleep(2.5)
        print("Credits to Mr. Nelson Rios of Yale University Dept. of Environmental Science for his guidance and support in this project.")
        time.sleep(2.5)
        print("Coded By Vincenzo D'Aria, all rights reserved")
        time.sleep(10)
        exit()
    else:
        print("Okay, be sure to come back later and get coding")
        time.sleep(2)
        print('Bye Now!')
        time.sleep(2)
        exit()
FirstPythonLesson()
